Dapper.SimpleCRUD-master/Dapper.SimpleCRUD-master/DemoWebsite/Controllers/GUIDTestController.cs
using System;
using System.Collections.Generic;
using System.Data.Common;
using System.Web.Mvc;
using Dapper;
using DemoWebsite.ViewModels;

namespace DemoWebsite.Controllers
{
    public class GUIDTestController : Controller
    {
        //
        // GET: /Home/
        private DbConnection _connection;

        public ActionResult Index()
        {
            return RedirectToAction("List");
        }
        public ActionResult List()
        {
            IEnumerable<GUIDTestViewModel> result;
            using (_connection = Utilities.GetOpenConnection())
            {
                result = _connection.GetList<GUIDTestViewModel>();
            }
            return View(result);
        }

        public ActionResult Details(string id)
        {
            GUIDTestViewModel result;
            using (_connection = Utilities.GetOpenConnection())
            {
                result = _connection.Get<GUIDTestViewModel>(id);
            }
            return View(result);
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(GUIDTestViewModel model)
        {
            if (ModelState.IsValid)
            {
                using (_connection = Utilities.GetOpenConnection())
                {
                    _connection.Insert<Guid, GUIDTestViewModel>(model);
                }
                return RedirectToAction("index");
            }
            return View(model);
        }

        public ActionResult Edit(string id)
        {
            GUIDTestViewModel model;
            using (_connection = Utilities.GetOpenConnection())
            {
                model = _connection.Get<GUIDTestViewModel>(id);
            }
            return View(model);
        }

        [HttpPost]
        public ActionResult Edit(GUIDTestViewModel model)
        {
            if (ModelState.IsValid)
            {
                using (_connection = Utilities.GetOpenConnection())
                {
                    _connection.Update(model);
                }
                return RedirectToAction("index");
            }

            return View(model);
        }

        public ActionResult Delete(string id)
        {
            using (_connection = Utilities.GetOpenConnection())
            {
                _connection.Delete<GUIDTestViewModel>(id);
            }
            return RedirectToAction("index");
        }


    }
}

Dapper.SimpleCRUD-master/Dapper.SimpleCRUD-master/DemoWebsite/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Dapper.SimpleCRUD</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <link href="http://bootswatch.com/paper/bootstrap.min.css" type="text/css" rel="stylesheet" />

</head>
<body>
    <div class="navbar navbar-default navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Dapper.SimpleCRUD", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("Car", "Index", "Car")</li>
                    <li>@Html.ActionLink("User", "Index", "User")</li>
                    <li>@Html.ActionLink("GUID", "Index", "GUIDTest")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Dapper.SimpleCRUD</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>